k9s:
  liveViewAutoRefresh: false
  # screenDumpDir: /home/someuser/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    # skin: stock-cust
    skin: monokai-cust
    # skin: axual
    # skin: gruvbox-dark
    # skin: monokai
    # skin: narsingh
    # skin: nightfox
    # skin: one-dark
    # skin: rose-pine-moon
    # skin: rose-pine
    # skin: snazzy
    # skin: solarized-dark
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
